[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
hyle_contract = { git = "https://github.com/hyle-org/hyle-cosmos.git", branch = "main" }
risc0-zkvm = { version = "1.0.5" }
